version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"

  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    command:
      - "--mongo-addr=mongodb://mongo:27017"

  prod:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    restart: always
    command:
      - "--database-name=cfrss"
      - "--mongo-addr=${MONGO_ADDR}"
      - "--enable-cf-scheduler=true"
      - "--environment=prod"